version: '3'

includes:
  infra:
    taskfile: infra/Taskfile.yml
    dir: infra

  web:app:
    taskfile: apps/web/spa/Taskfile.yml
    dir: apps/web/spa

  web:infra:
    taskfile: apps/web/infra/foundation/Taskfile.yml
    dir: apps/web/infra/foundation

  web:domain-mapping:
    taskfile: apps/web/infra/domain-mapping/Taskfile.yml
    dir: apps/web/infra/domain-mapping

  api:impl:
    taskfile: backend/api/impl/Taskfile.yml
    dir: backend/api/impl

  backend:infra:
    taskfile: backend/infra/Taskfile.yml
    dir: backend/infra

  cli:
    taskfile: cli/Taskfile.yml
    dir: cli

tasks:
  github-ci:lint:
    desc: Lint GitHub workflows
    sources:
      - '.github/workflows/*.yml'
    cmds:
      - github-ci lint

  github-ci:fixLint:
    desc: Fix lint issues in GitHub workflows
    sources:
      - '.github/workflows/*.yml'
    cmds:
      - github-ci lint --fix

  github-ci:upgrade:
    desc: Upgrade GitHub workflow actions to the latest versions
    cmds:
      - github-ci upgrade

  checkFormatting-all:
    desc: Check formatting for the entire codebase
    deps:
      - github-ci:lint
      - infra:checkFormatting
      - web:app:checkFormatting
      - web:infra:checkFormatting
      - web:domain-mapping:checkFormatting
      - api:impl:checkFormatting
      - backend:infra:checkFormatting
      - cli:checkFormatting

  fixFormatting-all:
    desc: Fix formatting for the entire codebase
    deps:
      - github-ci:fixLint
      - infra:fixFormatting
      - web:app:fixFormatting
      - web:infra:fixFormatting
      - web:domain-mapping:fixFormatting
      - api:impl:fixFormatting
      - backend:infra:fixFormatting
      - cli:fixFormatting

  lint-all:
    desc: Lint the entire codebase
    deps:
      - github-ci:lint
      - infra:lint
      - web:app:lint
      - web:infra:lint
      - web:domain-mapping:lint
      - api:impl:lint
      - backend:infra:lint
      - cli:lint

  analyze-all:
    desc: Analyze the entire codebase
    deps:
      - infra:validate
      - web:app:analyze
      - web:infra:validate
      - web:domain-mapping:validate
      - api:impl:compile
      - backend:infra:validate
      - cli:compile

  run:
    desc: Run the frontend and the API locally
    deps:
      - web:app:run
      - api:impl:run
