[versions]
detekt = "1.23.8"
google-cloud-libraries-bom = "26.83.0"
kotlin = "2.3.20"
kotlinx-serialization = "1.9.0"
ktfmt = "0.26.0"
shadow = "9.4.2"
versionCatalogUpdate = "1.1.0"

[libraries]
clikt = "com.github.ajalt.clikt:clikt-jvm:5.1.0"
google-cloud-libraries-bom = { module = "com.google.cloud:libraries-bom", version.ref = "google-cloud-libraries-bom" }
google-cloud-storage = { module = "com.google.cloud:google-cloud-storage" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
