syntax = "proto3";

// 🎨 TEMPLATE EJECT: Change the Protobuf package
package medusa.counter.v1;

option java_multiple_files = true;

// 🎨 TEMPLATE EJECT: Update this Java package reference
option java_package = "software.medusa.counter.v1";

// 🎨 TEMPLATE EJECT: Change the service name
service CounterService {
  rpc GetCount(GetCountRequest) returns (GetCountResponse);
  rpc Increment(IncrementRequest) returns (IncrementResponse);
  rpc Decrement(DecrementRequest) returns (DecrementResponse);
}

message GetCountRequest {}

message GetCountResponse {
  int32 count = 1;
}

message IncrementRequest {}

message IncrementResponse {
  int32 count = 1;
}

message DecrementRequest {}

message DecrementResponse {
  int32 count = 1;
}
