name: Check PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-workflows:
    name: workflows
    uses: ./.github/workflows/check-workflows.yml

  check-infra:
    name: infra
    uses: ./.github/workflows/check-infra.yml

  check-web-infra:
    name: web (infra)
    uses: ./.github/workflows/check-web-infra.yml
    secrets: inherit

    permissions:
      contents: read
      id-token: write
      pull-requests: write

  check-web-domain-mapping:
    name: web (domain mapping)
    uses: ./.github/workflows/check-web-domain-mapping.yml

  check-edge-rules:
    name: edge rules
    uses: ./.github/workflows/check-edge-rules.yml

  check-web-spa:
    name: web (SPA)
    uses: ./.github/workflows/check-web-spa.yml

  check-backend-infra:
    name: backend (infra)
    uses: ./.github/workflows/check-backend-infra.yml
    secrets: inherit

    permissions:
      contents: read
      id-token: write
      pull-requests: write

  check-api-impl:
    name: api (implementation)
    uses: ./.github/workflows/check-api-impl.yml

  check-cli:
    name: cli
    uses: ./.github/workflows/check-cli.yml

  check-docker-connector:
    name: docker-connector
    uses: ./.github/workflows/check-docker-connector.yml

  check-token-format:
    name: token-format
    uses: ./.github/workflows/check-token-format.yml

  check-front-door-refresher:
    name: front-door-refresher
    uses: ./.github/workflows/check-front-door-refresher.yml
