name: Deploy API

on:
  push:
    branches: ["trunk/*"]
    paths:
      - "backend/api/impl/**"

  workflow_dispatch:

permissions:
  contents: read

env:
  JAVA_VERSION: 21
  NO_COLOR: 1

  # Exact image path is arbitrary (as long as it's unique)
  IMAGE_REF: ${{ vars.GCP_AR_REPO_ENDPOINT }}/api/${{ github.sha }}

  SERVICE_PATH: backend/api/impl

jobs:
  deploy-service:
    name: Deploy service
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ vars.GCP_CICD_WI_PROVIDER_NAME }}
          service_account: ${{ vars.GCP_CICD_SA_EMAIL }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ vars.GCP_AR_REPO_HOSTNAME }} --quiet

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4

      - name: Build and push image
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          ../../../gradlew gcp:jib \
            -Pjib.imageRef=${{ env.IMAGE_REF }} \
            -Pjib.imageTag=${{ github.sha }} \
            --stacktrace --info

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.GCP_API_RUN_SERVICE_NAME }} \
            --project=${{ vars.GCP_PROJECT_ID }} \
            --region=${{ vars.GCP_PRIMARY_LOCATION }} \
            --image=${{ env.IMAGE_REF }} \
            --quiet
          gcloud run services describe ${{ vars.GCP_API_RUN_SERVICE_NAME }} \
            --project=${{ vars.GCP_PROJECT_ID }} \
            --region=${{ vars.GCP_PRIMARY_LOCATION }} \
            --format='value(status.url)' | tee service-url.txt
          {
            echo '## Cloud Run deployment'
            echo ''
            echo "- Service URL: [$(cat service-url.txt)]($(cat service-url.txt))"
          } >> "$GITHUB_STEP_SUMMARY"
